## parameters for ecbsr
scale: 2
colors: 1
m_ecbsr: 4
c_ecbsr: 8
idt_ecbsr: 0
act_type: 'prelu'
pretrain: Null

## parameters for model training
patch_size: 256
batch_size: 64
data_repeat: 64
data_augment: 1
epochs: 1
log_every: 10
test_every: 1
log_path: "./experiments"
lr: 0.0020
store_in_ram: 1

## hardware specification
gpu_id: 0
threads: 4

## data specification
div2k_hr_path: '/remote-home/share/DATA/super_resolution/DIV2K/DIV2K_train_HR'
div2k_lr_path: '/remote-home/share/DATA/super_resolution/DIV2K/DIV2K_train_LR_bicubic'
set5_hr_path: '/remote-home/share/DATA/super_resolution/Set5/HR'
set5_lr_path: '/remote-home/share/DATA/super_resolution/Set5/LR_bicubic'
set14_hr_path: '/remote-home/share/DATA/super_resolution/Set14/HR'
set14_lr_path: '/remote-home/share/DATA/super_resolution/Set14/LR_bicubic'
b100_hr_path: '/remote-home/share/DATA/super_resolution/B100/HR'
b100_lr_path: '/remote-home/share/DATA/super_resolution/B100/LR_bicubic'
u100_hr_path: '/remote-home/share/DATA/super_resolution/Urban100/HR'
u100_lr_path: '/remote-home/share/DATA/super_resolution/Urban100/LR_bicubic'
manga109_hr_path: '/remote-home/share/DATA/super_resolution/Manga109/HR'
manga109_lr_path: '/remote-home/share/DATA/super_resolution/Manga109/LR_bicubic'